### PR TITLE
augmented RunWorkflow and fixed tests

### LINKED ISSUE #1577: Fix unit tests
ensure `devtools::test()` passes with no errors

## Notes:
- there are now `mappings` and `counts` yaml files being included in `MakeWorkflowList`
- `RunWorkflow` is experiencing some issues with working through the appropriate level of list output from `MakeWorkflowList`.
- `mapping.yaml` workflow seems to be intended to create the df inputs for the kri workflow yaml files, but `RunStep` on the mapping.yaml is creating error when evaluating SQL query (RunStep seems to be setup for kri/cou workflows)

### PR DESCRIPTION
**Pull request by andersonjake1988**
fix #1577 

for the visualization tests and widgets I added skip until those functions are finalized with the new workflow

### CODE REVIEW

**Comment by andersonjake1988** [comment]
devtools::test()
devtools::test_coverage()
devtools::check()

all pass locally, looking into github workflows

**Comment by lauramaxwell** [comment]
Looks like `covr::test_coverage()` is failing in the workflow - is it passing locally?

File: R/RunWorkflow.R [hunk 1]
```diff
@@ -30,28 +30,47 @@
 #' @export
 
 RunWorkflow <- function(lWorkflow, lData) {
-  cli::cli_h1(paste0("Initializing `", lWorkflow$meta$file, "` Workflow"))
+  output <- imap(lWorkflow, function(workflow, name){
```
Comment (lauramaxwell) [inline R/RunWorkflow.R:36]: Just to clarify this update to RunWorkflow- is the idea here to be able to get `lResults` by just running `RunWorkflow(lWorkflow=wf_metrics, lData=lMapped))` where `wf_metrics` is the list of all workflows for all KRIs? currently we run `lResults <- wf_metrics %>% map(~RunWorkflow(lWorkflow=.x, lData=lMapped))` to do this.

**Review by lauramaxwell — COMMENTED** [review]
one clarifying question, then i will approve and merge!

File: R/RunWorkflow.R (hunk 1 above)
Comment (andersonjake1988) [reply R/RunWorkflow.R:36]: yes, that was the idea. I moved the map to the interior, and it will work with one or more workflows, so it will be simpler for the user

**Comment by lauramaxwell** [comment]
@jwildfire The adjustment to `RunWorkflow()` made in this PR means that we have to make some small adjustments to the data pipeline script. Primarily- all dfs made in a workflow are stored in a `lResults` object instead of `lData` and we take the full `wf_mapping` list in `MakeWorkflowList()` instead of just the first element as we did before. let me know if this is good on your end, and i'll merge this in and post the workflow change to the comments on this [PR](https://github.com/Gilead-BioStats/gsm/pull/1545)(?)

```
# Prepare Workflows
wf_mapping <- MakeWorkflowList(strNames="mapping")
wf_metrics <- MakeWorkflowList(strNames=paste0("kri",sprintf("%04d", 1:12)))
dfMetrics <- wf_metrics %>% map_df(~.x$meta)

# Import Site+Study Metadata
dfStudy<-clindata::ctms_study %>% rename(StudyID = protocol_number)
dfSite<- clindata::ctms_site %>% rename(SiteID = site_num)

# Pull Raw Data - this will overwrite the previous data pull
lRaw <- gsm::UseClindata(
  list(
    "dfSUBJ" = "clindata::rawplus_dm",
    "dfAE" = "clindata::rawplus_ae",
    "dfPD" = "clindata::ctms_protdev",
    "dfLB" = "clindata::rawplus_lb",
    "dfSTUDCOMP" = "clindata::rawplus_studcomp",
    "dfSDRGCOMP" = "clindata::rawplus_sdrgcomp %>%
      dplyr::filter(.data$phase == 'Blinded Study Drug Completion')",
    "dfDATACHG" = "clindata::edc_data_points",
    "dfDATAENT" = "clindata::edc_data_pages",
    "dfQUERY" = "clindata::edc_queries",
    "dfENROLL" = "clindata::rawplus_enroll"
  )
)

# Create Mapped Data
lMapped <- RunWorkflow(lWorkflow = wf_mapping, lData = lRaw)
# Run Metrics
lResults <- RunWorkflow(lWorkflow=wf_metrics, lData=lMapped$mapping$lResults)

dfBounds <- lResults %>% 
  imap_dfr(~.x$lResults$dfBounds %>% mutate(MetricID = .y)) %>%
  mutate(StudyID = "ABC-123") %>%
  mutate(SnapshotDate = Sys.Date())

dfSummary <- lResults %>% 
  imap_dfr(~.x$lResults$dfSummary %>% mutate(MetricID = .y)) %>%
  mutate(StudyID = "ABC-123") %>%
  mutate(SnapshotDate = Sys.Date())

lCharts <- unique(dfSummary$MetricID) %>% map(~Visualize_Metric(
  dfSummary = dfSummary, 
  dfBounds = dfBounds, 
  dfSite = dfSite,
  dfMetrics = dfMetrics, 
  strMetricID = .x
)
) %>% setNames(unique(dfSummary$MetricID)) 
```

File: R/RunWorkflow.R (hunk 1 above)
Comment (jwildfire) [reply R/RunWorkflow.R:36]: I do want to refactor RunWorkflow, and I think this is a step in the right direction, but I would like to hold off on the change for now and deal with it in a separate PR. I *really* want to keep the workflow functionality simple. One of the big problems with v1 was that the various workflow functions we created were way too complex. 

A few things to consider: 
- We do want to support running a single workflow (e.g. [mapping](https://github.com/Gilead-BioStats/gsm/blob/4f2b52d4ab453f7ae1b9af9f492504010caa73ea/inst/demo/LongitudinalReport.R#L66)), so we'd need to add logic for that. 
- I want to think through how we use `lResults` vs. `lData` in the object we are returning. If possible, we should just have one of the 2, not both. 
- I want to think about how to "chain" workflows together. Is there any reason we can't call one workflow as a step in a larger workflow? 
- I want to move some of our standard charting and reporting functionality in to workflows as well. Want to make sure updates support that. 

I think we should tackle these changes after the reporting updates are done. It's possible that we'll want to hold off and make the updates as part of v2.1. 

@lauramaxwell @andersonjake1988 for now, let's revert this file to it's previous version and create an issue and PR summarizing the changes needed. We can tackle in the coming weeks.

**Review by jwildfire — CHANGES_REQUESTED** [review]
See notes on RunWorkflow

File: R/Report_KRI.R [hunk 2]
```diff
@@ -36,35 +37,44 @@
 #' )
 #'
 #' # Create Mapped Data
-#' lMapped <- RunWorkflow(lWorkflow = wf_mapping, lData = lRaw)$lData
+#' lMapped <- RunWorkflow(lWorkflow = wf_mapping, lData = lRaw)$mapping$lResults
```
Comment (lauramaxwell) [inline R/Report_KRI.R:40]: This reflects the `RunWorkflow()` changes that we've reverted. Can we make sure to revert these as well? There are also references to `$lResults` throughout other scripts and header examples. Thanks!!

**Review by lauramaxwell — CHANGES_REQUESTED** [review]
a few references to the `RunWorkflow()` edits still lingering. should be a quick fix

**Review by lauramaxwell — APPROVED** [review]

**Review by jwildfire — APPROVED** [review]
