### PR TITLE
Closes #1877 and #1883 addressing bugfixes related to `StudyID` on `Report_Setup()` and `reportingXXXX` datasets

### LINKED ISSUE #1877: Bugfix: `Study_Setup` should pull study ID from `dfGroups$GroupID`.
## Expected Behavior
Study ID appears at top of report and in group breakdown text beneath group overview table.

## Current Behavior
`Study_Setup` looks for `protocol_number` or `protocol_title` from list of parameters in `dfGroups` where `GroupLevel == 'Study'`, and if absent the report displays _Unknown_.

image

image

## Possible Solution
```
output$StudyID <- dfGroups %>%
    filter(.data$GroupLevel == 'Study') %>%
    pull('GroupID') %>%
    unique()
```

## Steps to Reproduce

1. Remove parameters `protocol_number` and `protocol_title` from `dfGroups`.
2. Run `Report_KRI`.

### LINKED ISSUE #1883: Bugfix: Study ID in reportingGroups and reportingGroups_country
## Expected Behavior
```r
gsm::reportingGroups_country %>% 
  dplyr::filter(GroupLevel == "Study") %>% 
  dplyr::distinct(GroupID)

# OR
gsm::reportingGroups %>% 
  dplyr::filter(GroupLevel == "Study") %>% 
  dplyr::distinct(GroupID)
```
Expected:
```r
         GroupID
1 AA-AA-000-0000
```

## Current Behavior
```r
         GroupID
1        ABC-123
2 AA-AA-000-0000
```

## Possible Solution
In `data-raw/simluate_longitudinal_data.R`, several lines use "ABC-123" for the StudyID. I suspect all of these should be "AA-AA-000-0000", although it's possible some of them really should be "ABC-123" to match up sample data from clindata.

## Steps to Reproduce

1.
2.
3.
4.

### PR DESCRIPTION
**Pull request by zdz2101**
## Overview

- Updated `Report_Setup()` to pull out `StudyID` correctly
- Identified that the `gsm::reportingXXXX` datasets were not up to date with the newest workflows
- Modified `data-raw/simulate_longitudinal_data.R` to generate new datasets
- Created new function in `data-specs.R` that creates the data frame dimensions statement for the format in case datasets were "incorrect" so no need to manually check

- Closes #1877 
- Closes #1883

### CODE REVIEW

File: R/Report_Setup.R [hunk 1]
```diff
@@ -44,13 +44,10 @@ Report_Setup <- function(dfGroups = NULL, dfMetrics = NULL, dfResults = NULL) {
...
     as.list()
 
-  if ("protocol_number" %in% names(output$lStudy)) {
-    output$StudyID <- output$lStudy$protocol_number
-  } else if ("protocol_title" %in% names(output$lStudy)) {
-    output$StudyID <- output$lStudy$protocol_title
-  } else {
-    output$StudyID <- "Unknown"
-  }
+  output$StudyID <- dfGroups %>%
```
Comment (zdz2101) [inline R/Report_Setup.R:47]: @samussiah here is the implementation for #1877 , everything else has to do with the updates with the reporting data and its implications across our examples, tests, etc.

File: R/Report_MetricTable.R [hunk 2]
```diff
@@ -20,7 +20,7 @@
 #' # site-level report
 #' Report_MetricTable(
 #'   dfResults = reportingResults %>%
-#'     dplyr::filter(.data$MetricID == "kri0001") %>%
+#'     dplyr::filter(.data$MetricID == "Analysis_kri0001") %>%
```
Comment (zdz2101) [inline R/Report_MetricTable.R:23]: A lot of fixes look like this since we changed how MetricID is make in `MakeMetric()`

File: R/data-specs.R [hunk 3]
```diff
@@ -180,3 +190,7 @@
 #' }
 #' @source Generated from `reportingResults_country.csv` dataset in the `gsm` package.
 "reportingResults_country"
+
+df_dim_desc <- function(df){
```
Comment (zdz2101) [inline R/data-specs.R:194]: Felt like a good idea to have the dimensions programmatically render the dimensions of the dataframe statement

File: data-raw/simulate_longitudinal_data.R [hunk 4]
```diff
@@ -185,9 +175,9 @@ for (i in 1:12) {
   dfParticipants <-
     AddParticipants(
       dfParticipants,
-      studyid = "ABC-123",
+      studyid = "AA-AA-000-0000",
```
Comment (zdz2101) [inline data-raw/simulate_longitudinal_data.R:178]: Maybe I didn't have a fresh session or something with the set.seed() situation but my results & etc. don't quite perfectly match what we originally had so this had small implications for the testthat stuff

File: tests/testthat/test-Report_MetricTable.R [hunk 5]
```diff
@@ -9,16 +9,16 @@ test_that("Correct data structure when proper dataframe is passed", {
     dplyr::filter(MetricID == unique(reportingResults$MetricID)[1])
   result <- Report_MetricTable(reportingResults_filt, reportingGroups)
   expect_s3_class(result, "gt_tbl")
-  expect_true(any(grepl("162", result)))
-  expect_true(any(grepl("Kimler", result)))
+  #expect_true(any(grepl("162", result)))
```
Comment (zdz2101) [inline tests/testthat/test-Report_MetricTable.R:12]: with "new" results, I'm not quite matching the hard coded testthat results all the time, might be a result of recreating it incorrectly, but can modify tests to be more data agnostic or hard code new ones?

File: data-raw/simulate_longitudinal_data.R (hunk 4 above)
Comment (zdz2101) [reply data-raw/simulate_longitudinal_data.R:178]: @lauramaxwell in particular I'd probably need a solid audit/double check what was done here in `data-raw/simulate_longitudinal_data.R`, can set the for loop to (i in 1:2) if you want to speed up/check the structure of everything inside is fed and done correctly

File: R/Report_Setup.R (hunk 1 above)
Comment (samussiah) [reply R/Report_Setup.R:47]: Looks great @zdz2101!

File: R/Report_MetricTable.R (hunk 2 above)
Comment (samussiah) [reply R/Report_MetricTable.R:23]: Thanks for slogging through the updates.

File: data-raw/simulate_longitudinal_data.R (hunk 4 above)
Comment (lauramaxwell) [reply data-raw/simulate_longitudinal_data.R:178]: taking a look now!

Comment (lauramaxwell) [reply data-raw/simulate_longitudinal_data.R:178]: in looking into this, i think i originally overcomplicated the country-fication of the simulated data. i'm going to dig into this this afternoon and see if can simplify the process. The updating you did for v2.1 updates looks great, so that will definitely stay.

Comment (lauramaxwell) [reply data-raw/simulate_longitudinal_data.R:178]: okay, after making some changes, I came back around to this approach in the end, so we're going to keep it. re: testing differences, it makes sense that there are differences because even with the same seed, you had to add some lines of code, which impacted the R session so that sampling was not identical.

File: tests/testthat/test-Report_MetricTable.R (hunk 5 above)
Comment (lauramaxwell) [reply tests/testthat/test-Report_MetricTable.R:12]: you can modify tests to be more data agnostic

**Review by lauramaxwell — CHANGES_REQUESTED** [review]
looks good! just need to make those test changes and I think we should be gtg

File: data-raw/simulate_longitudinal_data.R [hunk 6]
```diff
@@ -213,7 +203,7 @@ for (i in 1:12) {
                             dfParticipants = dfParticipants)
   dfQUERY <- AddQUERY(df = dfQUERY,
                       dfParticipants = dfParticipants)
-  dfDATACHG <- AddDATACHG(df = dfSTUDCOMP,
+  dfDATACHG <- AddDATACHG(df = dfDATACHG,
```
Comment (lauramaxwell) [inline data-raw/simulate_longitudinal_data.R:206]: @zdz2101 I found this typo, so i think simulation needs to be run again. it was existing prior to this PR.

**Review by lauramaxwell — APPROVED** [review]
