### PR TITLE
Augment_Snapshot update 

### LINKED ISSUE #1347: Bugfix: `Augment_Snapshot` tries to read `<latest-snapshot>/results_summary.csv` even if it doesn't exist.
## Current Behavior
If the latest snapshot folder is empty, it will error out. 

## Steps to Reproduce

1.
2.
3.
4.

### LINKED ISSUE #1348: Bugfix: `Augment_Snapshot` assumes all files in `cPath` are dated folders.
## Steps to Reproduce

1.
2.
3.
4.

### PR DESCRIPTION
**Pull request by andersonjake1988**
added new functions for snapshot directory and date extraction and fixed augment snapshot / stacked snapshot bug

fix  #1347 
fix  #1348 

## Test Notes/Sample Code

Notes:

### CODE REVIEW

File: R/util-ExtractSnapshotDate.R [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+  output <- purrr::map(snapshot_paths, ~paste0(., "/", acceptable_files)) %>%
+    purrr::set_names(stringr::str_extract(snapshot_paths, "([^/]+$)")) %>%
+    map(., ~read.csv(.[file.exists(.)][1], nrows=1) %>%
+          pull(gsm_analysis_date)) %>%
+    tibble::as_tibble() %>%
+    t() %>%
+    as.data.frame() %>%
+    tibble::rownames_to_column() %>%
+    `colnames<-`(c("foldername", "snapshot_date")) %>%
+    mutate(snapshot_date = as.Date(snapshot_date))
```
Comment (mattroumaya) [inline R/util-ExtractSnapshotDate.R:32]: This is great! I wanted to understand what was going on here, and am showing a different idea since `imap` could be helpful for slightly shorter code. Feel free to change or keep as-is.

```
  output <- purrr::map(snapshot_paths, ~paste0(., "/", acceptable_files)) %>%
    purrr::set_names(stringr::str_extract(snapshot_paths, "([^/]+$)")) %>%
    purrr::imap(., ~read.csv(.[file.exists(.)][1], nrows=1) %>% 
                  mutate(foldername = as.Date(.y))) %>% 
    bind_rows() %>% 
    select("foldername", "snapshot_date" = "gsm_analysis_date")
```

File: R/Augment_Snapshot.R [hunk 2]
```diff
@@ -87,57 +87,58 @@ Augment_Snapshot <- function(
...
+        for (kri in old_workflows[[old_date]]) {
+          lSnapshot$lStudyAssessResults[[kri]] <- old_snapshots[[old_date]]$lStudyAssessResults[[kri]]
+        }
       }
     }
-    lSnapshot[["lStatus"]] <- is_current %>%
-      `colnames<-`(c("Workflow ID", "Latest Snapshot", "Currently Active"))
+
+    lSnapshot[["lStatus"]] <- status %>%
+      `colnames<-`(c("Workflow ID", "Latest Snapshot", "Currently Active", "Folder Name"))
```
Comment (mattroumaya) [inline R/Augment_Snapshot.R:141]: This is nitpicky but I think I'd prefer to use `rename()` here instead of `colnames` just to stay consistent with the tidyverse-style we're using in gsm.

**Review by mattroumaya — APPROVED** [review]
This is great! Added some comments but good to merge as-is.

File: R/util-ExtractSnapshotDate.R (hunk 1 above)
Comment (andersonjake1988) [reply R/util-ExtractSnapshotDate.R]: I like it thanks!
